cp crouton-noroot chromeOSLinux-noroot
cp croutonfindnacl chromeOSLinuxfindnacl 
cp croutonurlhandler chromeOSLinuxlhandler
cp crouton-unity-autostart chromeOSLinux-unity-autostart 
cp croutonnotify chromeOSLinuxnotify
cp croutonversion chromeOSLinuxversion
cp croutonclip chromeOSLinuxclip
cp croutonpowerd chromeOSLinuxpowerd
cp croutonxinitrc-wrapper chromeOSLinuxxinitrc-wrapper
cp croutoncycle chromeOSLinuxcycle
cp croutontriggerd chromeOSLinuxtriggerd

