#!/bin/bash -e
# Copyright (c) 2022 The chromeOSLinux Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file is sourced from main.sh to update distro-specific defaults.
# It must set at least ARCH and MIRROR if not already specified.

if [ -z "$ARCH" ]; then
    ARCH="`uname -m`"
fi

case "$ARCH" in
x86 | i?86) ARCH="i386";;
x86_64 | amd64) ARCH="amd64";;
arm64 | aarch64) ARCH="arm64";;
arm*) ARCH="armhf";;
*) error 2 "Invalid architecture '$ARCH'.";;
esac


if [ -z "$MIRROR" ]; then
    if [ "$ARCH" = 'amd64' -o "$ARCH" = 'i386' ]; then
        MIRROR="${CROUTON_MIRROR_opensuse:-https://mirrors.edge.kernel.org/opensuse/distribution/openSUSE-current/repo/oss/x86_64/}"
    else
        MIRROR="${CROUTON_MIRROR_opensuse:-https://mirrors.edge.kernel.org/opensuse/distribution/openSUSE-current/repo/oss/aarch64/}"
    fi
fi

