#!/bin/bash -e
# Copyright (c) Mon Jan 23 10:52:34 PST 2023 The chromeOSLinux Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if [ -z "$XMETHOD" ]; then
    if [ -f '/etc/chromeOSLinux/xmethod' ]; then
        read -r XMETHOD _ < /etc/chromeOSLinux/xmethod
    else
        echo 'X11 backend not set.' 1>&2
        exit 1
    fi
fi

xserverrc="/etc/chromeOSLinux/xserverrc-${XMETHOD%%-*}"
if [ "${XMETHOD##*/}" != "$XMETHOD" -o ! -f "$xserverrc" ]; then
    echo "Invalid X11 backend '$XMETHOD'" 1>&2
    exit 2
fi

. "$xserverrc"
