#!/bin/bash -e
# Copyright (c) Mon Jan 23 10:52:34 PST 2023 The chromeOSLinux Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

logfile="/tmp/Xorg.chromeOSLinux.$$.log"
for arg in "$@"; do
    disp="`echo "$arg" | sed -n 's/^\:\([0-9]*\)$/\1/p'`"
    if [ -n "$disp" ]; then
        logfile="/tmp/Xorg.chromeOSLinux.$disp.log"
    fi
done

if [ "${XMETHOD%%-*}" != 'xiwi' ]; then
    export XMETHOD='xiwi'
fi
XARGS="-nolisten tcp -config xorg-dummy.conf -logfile $logfile"
if [ -f /etc/chromeOSLinux/xserverrc-local ]; then
    . /etc/chromeOSLinux/xserverrc-local
fi

exec /usr/bin/Xorg $XARGS "$@"
