#!/bin/bash -e
# Copyright (c) Mon Jan 23 10:52:34 PST 2023 The chromeOSLinux Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

REQUIRES='x11'
DESCRIPTION='Touchscreen and dev support.'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

install ukui-touchpadserver libukui-touchpadclient-dev



TIPS="$TIPS touchpad settings service process
UKUI interface provides the interface for system configuration and related libraries.
The package contains touchpad settings service process."
