#!/bin/bash -e
# Copyright (c) 2022 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='gnome'
DESCRIPTION='Installs GNOME along with common applications.'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install gnome gnome-devel gnome-platform-devel
