#!/bin/bash -e
# Copyright (c) 2022 The chromeOSLinux Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION='gtk-3 based tools'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
##install_dummy network-manager network-manager-gnome
install *gtk-3*



