#!/bin/bash -e
# Copyright (c) 2022 The chromeOSLinux Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
DESCRIPTION='Installs the LXDE desktop environment. (Approx. 200MB)'
HOSTBIN='startlxde'
CHROOTBIN='chromeOSLinux-noroot startlxde'
. "${TARGETSDIR:="$PWD"}/common"
### Append to prepare.sh:
install lxde
TIPS="$TIPS
You can start LXDE via the startlxde host command: sudo startlxde
"
