#!/bin/bash -e
# Copyright (c) 2014 The chromeOSLinux Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
DESCRIPTION='Installs the mate desktop environment. (Approx. 250MB)'
HOSTBIN='startmate'
CHROOTBIN='chromeOSLinux-noroot startmate'
. "${TARGETSDIR:="$PWD"}/common"

install mate mate-goodies
TIPS="$TIPS
You can start mate via the startmate host command: sudo startmate
"
