#!/bin/bash -e
# Copyright (c) 2022 The chromeOSLinux Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
DESCRIPTION='tools'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

install net-tools git partitionmanager golang firefox* \
bison cmake nano gedit gedit-plugins kwrite vlc \
vlc-plugin-access-extra gnome-disk-utility gnome-sound-recorder \
ninja-build meson cmake make
