#!/bin/bash -e
# Copyright (c) 2022 The chromeOSLinux Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
DESCRIPTION='Installs the Unity desktop environment. (Approx. 700MB)'
HOSTBIN='startunity'
CHROOTBIN='chromeOSLinux-noroot startunity gnome-session-wrapper chromeOSLinux-unity-autostart'
CHROOTETC='unity-autostart.desktop unity-profiled'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
# Note that whitespace is important for syntax.
# See distropkgs method in installer/prepare.sh
install unity  gnome-session nautilus gnome-terminal  \
    # Set up global autostart script
    mkdir -p "$autostartdir"
    ln -sfT /etc/chromeOSLinux/unity-autostart.desktop \
        "$autostartdir"/chromeOSLinux-unity-autostart.desktop

    # Set up profile.d
    chmod 755 /etc/chromeOSLinux/unity-profiled
    ln -sfT /etc/chromeOSLinux/unity-profiled /etc/profile.d/chromeOSLinux-unity-profiled.sh

TIPS="$TIPS
You can start Unity via the startunity host command: sudo startunity
"
